# SOPS configuration for encrypting secrets
# Defines which age keys can decrypt which files

keys:
  # Admin key (for editing secrets on your workstation)
  - &admin age17z3dr8u7tyr4h38hx9q47av7eszhha4h0huk9f2pu9r8q557t42qttj4cv

  # Shared homelab key (all VMs use this to decrypt)
  # This key is injected into all homelab VMs via Pulumi cloud-init
  - &homelab age1zppfe5xpzt77wgj5t9ajmd2v52xzkskgwtzd3y4u9el2hujeechss4ahek


creation_rules:
  # All homelab secrets (single rule for all hosts)
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin
          - *homelab
