{ config, pkgs, hostname, username, ... }:

{
  imports = [
    # Disko disk configuration for nixos-anywhere
    ./infra-01-disko.nix

    # Service modules
    ../modules/services/postgresql.nix
    ../modules/services/gitea.nix
    ../modules/services/adminer.nix
    ../modules/services/traefik.nix

    # Disabled services (uncomment when ready)
    #../modules/services/redis.nix
    #../modules/services/backup.nix  # Requires passphrase configuration
  ];

  # Bootloader - systemd-boot for UEFI
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # Hardware modules for Proxmox VM (Virtio/QEMU/KVM)
  boot.initrd.availableKernelModules = [
    # SATA/AHCI support
    "ahci"
    "sd_mod"
    "sr_mod"

    # Virtio support (critical for Proxmox/QEMU/KVM)
    "virtio_pci"
    "virtio_scsi"
    "virtio_blk"
    "virtio_net"
    "virtio_balloon"
    "virtio_console"

    # USB support
    "xhci_pci"
    "ehci_pci"
    "uas"
  ];

  boot.kernelModules = [ "kvm-intel" ];  # or "kvm-amd" for AMD CPUs

  # Note: fileSystems are auto-generated by Disko from infra-01-disko.nix

  # Enable serial console for Proxmox
  boot.kernelParams = [ "console=tty0" "console=ttyS0,115200" ];
  systemd.services."serial-getty@ttyS0" = {
    enable = true;
    wantedBy = [ "multi-user.target" ];
  };

  # Use latest kernel
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Networking
  networking = {
    hostName = hostname;
    useDHCP = false;
    useNetworkd = true;

    # Firewall (service-specific ports opened in service modules)
    firewall = {
      enable = true;
      allowedTCPPorts = [ 22 ];  # SSH
    };
  };

  # Static IP configuration via systemd-networkd
  systemd.network = {
    enable = true;
    networks."10-lan" = {
      matchConfig.Name = "ens18";
      networkConfig = {
        Address = "192.168.1.180/24";
        Gateway = "192.168.1.1";
        DNS = [ "192.168.1.1" ];
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Locale & timezone
  time.timeZone = "America/Toronto";
  i18n.defaultLocale = "en_CA.UTF-8";

  # SSH server for remote management
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password"; # Key-based auth only
      PasswordAuthentication = false;
    };
  };

  # Root user configuration
  users.users.root = {
    # Password for console access (change on first login)
    initialPassword = "nixos123";

    # SSH public keys
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILeIwbkY/hwG0ZOWh7zfoQmZaR58iGRG14QX4WiGQldI briggsy87@gmail.com"
    ];
  };

  # Additional server-specific packages (common packages in modules/common)
  environment.systemPackages = with pkgs; [
    # Advanced monitoring
    btop
    ncdu
    tree

    # Terminal tools
    tmux
    ncurses

    # Database clients
    postgresql
    redis

    # Backup tools
    borgbackup
  ];

  # Enable zsh for root
  programs.zsh.enable = true;
  users.users.root.shell = pkgs.zsh;

  # SOPS secrets management
  sops = {
    # Use shared homelab age key (injected by Pulumi via cloud-init)
    # This allows all homelab VMs to decrypt secrets without per-host key management
    age.keyFile = "/etc/sops/homelab-key.txt";

    # Default file for secrets
    defaultSopsFile = ../secrets/infra-01.yaml;

    # Define secrets to decrypt
    secrets = {
      aws_access_key_id = {};
      aws_secret_access_key = {};
      postgres_admin_password = {};
      gitea_db_password = {};
    };
  };

  # System state version (NixOS 25.05)
  system.stateVersion = "25.05";

  # Notes:
  # - All service data stored in /data/* (PostgreSQL, Redis, Gitea)
  # - Backups configured via backup.nix to backup /data
  # - Services accessible from K3s cluster via static IP (192.168.1.11)
  # - Gitea includes container registry for K3s images
}
